# Generated by Django 6.0.3 on 2026-03-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_courseclass_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
