# Generated by Django 6.0.3 on 2026-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_courseclass_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10),
        ),
    ]
